### ISSUE TITLE
[Bug] Weird Playlist Duplication bug

### ISSUE THREAD

**Issue by ImExiled** [musiqpad/mqp-server#9]
Well.... Playlists like to dupe songs. A lot.

http://i.imgur.com/CfR9AkB.png

The playlists above are imported straight from plug. I shouldn't have 721 tracks.

There are like 18 copies of "Nightcore - Senpai" down the list.

Please fix ;_;

**Comment by explodingcamera** [comment]
Just tried it too and I'm not having any problems, maybe check if your exported json had the duplicates in it?

**Comment by virtuaCode** [comment]
Same bug here...

![bug_media](https://cloud.githubusercontent.com/assets/16387293/13952149/121cd4cc-f035-11e5-8d8d-638ae7d0c35e.png)

**Comment by explodingcamera** [comment]
I was using leveldb so probably only using mysql

**Comment by virtuaCode** [comment]
It seems like only playlists that were imported as a file are affected by this bug.

**Comment by ImExiled** [comment]
Indeed. I don't like deleting many many copies of tracks via PhpMyAdmin. There are literally hundreds upon hundreds of dupes I would need to get rid of. Screencap: http://i.imgur.com/KgJg6lE.png

Also when I say hundreds upon hundreds of dupes, I dont mean hundreds of the same song. I mean hundreds of dupelicated tracks in general. Example in the screencap.

**Comment by foodbandlt** [comment]
I'll try to look into this a little deeper tonight.  @DerpgonCz wrote the MySQL code, so I've yet to look at it.

**Comment by ImExiled** [comment]
@foodbandlt Alright then ;3

**Comment by virtuaCode** [comment]
If you need a solution immediately you could delete all duplicates on the 'media' table and create a unique constraint for 'cid' and 'pid':

```
ALTER IGNORE TABLE media
ADD UNIQUE INDEX uq_media (pid, cid);
```

**Comment by ImExiled** [comment]
@virtuaCode Thanks for the help, i'll try when I get some free time.

**Comment by TheBanHammer** [comment]
Fixed in e548a8a

**Comment by ImExiled** [comment]
The amount of confusion with that close/reopen there :|

**Comment by foodbandlt** [comment]
We thought the issue was solved, but after more testing found that it wasn't.  Still needs to be looked into.

**Comment by ImGrumpy** [comment]
I have a couple of users commenting this morning that this https://github.com/musiqpad/mqp-server/issues/9#issuecomment-199803977 is true and still happening.  They are using the DT importer.  Looks like the import works OK, but on refresh they have multiple copies of each song.

**Comment by DerpgonCz** [comment]
@ImGrumpy I will try to check it today
